local _, FieldGuide = ...

FieldGuide.WEAPONS = {
    ["druid"] = {
        [1] = {
            ["id"] = 199,
            ["name"] = "Two-Handed Maces",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/inv_mace_04",
        },
        [2] = {
            ["id"] = 198,
            ["name"] = "One-Handed Maces",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/inv_mace_01",
        },
        [3] = {
            ["id"] = 15590,
            ["name"] = "Fist Weapons",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/inv_gauntlets_04",
        },
        [4] = {
            ["id"] = 227,
            ["name"] = "Staves",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/inv_staff_08",
        },
        [5] = {
            ["id"] = 1180,
            ["name"] = "Daggers",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/ability_steelmelee",
        }
    },
    ["hunter"] = {
        [1] = {
            ["id"] = 674,
            ["name"] = "Dual Wield",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/ability_dualwield",
        },
        [2] = {
            ["id"] = 200,
            ["name"] = "Polearms",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/inv_spear_06",
        },
        [3] = {
            ["id"] = 197,
            ["name"] = "Two-Handed Axes",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/inv_axe_04",
        },
        [4] = {
            ["id"] = 15590,
            ["name"] = "Fist Weapons",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/inv_gauntlets_04",
        },
        [5] = {
            ["id"] = 202,
            ["name"] = "Two-Handed Swords",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/ability_meleedamage",
        },
        [6] = {
            ["id"] = 196,
            ["name"] = "One-Handed Axes",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/inv_axe_01",
        },
        [7] = {
            ["id"] = 264,
            ["name"] = "Bows",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/inv_weapon_bow_05",
        },
        [8] = {
            ["id"] = 2567,
            ["name"] = "Thrown",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/inv_throwingknife_02",
        },
        [9] = {
            ["id"] = 227,
            ["name"] = "Staves",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/inv_staff_08",
        },
        [10] = {
            ["id"] = 201,
            ["name"] = "One-Handed Swords",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/ability_meleedamage",
        },
        [11] = {
            ["id"] = 266,
            ["name"] = "Guns",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/inv_weapon_rifle_01",
        },
        [12] = {
            ["id"] = 5011,
            ["name"] = "Crossbows",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/inv_weapon_crossbow_01",
        },
        [13] = {
            ["id"] = 3127,
            ["name"] = "Parry",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/ability_parry",
        },
        [14] = {
            ["id"] = 1180,
            ["name"] = "Daggers",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/ability_steelmelee",
        },
        [15] = {
            ["id"] = 2764,
            ["name"] = "Throw",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/ability_throw",
        },
    },
    ["mage"] = {
        [1] = {
            ["id"] = 227,
            ["name"] = "Staves",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/inv_staff_08",
        },
        [2] = {
            ["id"] = 201,
            ["name"] = "One-Handed Swords",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/ability_meleedamage",
        },
        [3] = {
            ["id"] = 1180,
            ["name"] = "Daggers",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/ability_steelmelee",
        },
        [4] = {
            ["id"] = 5019,
            ["name"] = "Shoot",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/ability_shootwand",
        },
        [5] = {
            ["id"] = 5009,
            ["name"] = "Wands",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/ability_shootwand",
        },
    },
    ["paladin"] = {
        [1] = {
            ["id"] = 200,
            ["name"] = "Polearms",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/inv_spear_06",
        },
        [2] = {
            ["id"] = 199,
            ["name"] = "Two-Handed Maces",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/inv_mace_04",
        },
        [3] = {
            ["id"] = 197,
            ["name"] = "Two-Handed Axes",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/inv_axe_04",
        },
        [4] = {
            ["id"] = 198,
            ["name"] = "One-Handed Maces",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/inv_mace_01",
        },
        [5] = {
            ["id"] = 202,
            ["name"] = "Two-Handed Swords",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/ability_meleedamage",
        },
        [6] = {
            ["id"] = 196,
            ["name"] = "One-Handed Axes",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/inv_axe_01",
        },
        [7] = {
            ["id"] = 201,
            ["name"] = "One-Handed Swords",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/ability_meleedamage",
        },
        [8] = {
            ["id"] = 107,
            ["name"] = "Block",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/ability_defend",
        },
        [9] = {
            ["id"] = 3127,
            ["name"] = "Parry",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/ability_parry",
        },
    },
    ["priest"] = {
        [1] = {
            ["id"] = 198,
            ["name"] = "One-Handed Maces",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/inv_mace_01",
        },
        [2] = {
            ["id"] = 227,
            ["name"] = "Staves",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/inv_staff_08",
        },
        [3] = {
            ["id"] = 1180,
            ["name"] = "Daggers",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/ability_steelmelee",
        },
        [4] = {
            ["id"] = 5019,
            ["name"] = "Shoot",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/ability_shootwand",
        },
        [5] = {
            ["id"] = 5009,
            ["name"] = "Wands",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/ability_shootwand",
        },
    },
    ["rogue"] = {
        [1] = {
            ["id"] = 674,
            ["name"] = "Dual Wield",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/ability_dualwield",
        },
        [2] = {
            ["id"] = 198,
            ["name"] = "One-Handed Maces",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/inv_mace_01",
        },
        [3] = {
            ["id"] = 15590,
            ["name"] = "Fist Weapons",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/inv_gauntlets_04",
        },
        [4] = {
            ["id"] = 264,
            ["name"] = "Bows",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/inv_weapon_bow_05",
        },
        [5] = {
            ["id"] = 2567,
            ["name"] = "Thrown",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/inv_throwingknife_02",
        },
        [6] = {
            ["id"] = 201,
            ["name"] = "One-Handed Swords",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/ability_meleedamage",
        },
        [7] = {
            ["id"] = 266,
            ["name"] = "Guns",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/inv_weapon_rifle_01",
        },
        [8] = {
            ["id"] = 5011,
            ["name"] = "Crossbows",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/inv_weapon_crossbow_01",
        },
        [9] = {
            ["id"] = 3127,
            ["name"] = "Parry",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/ability_parry",
        },
        [10] = {
            ["id"] = 1180,
            ["name"] = "Daggers",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/ability_steelmelee",
        },
        [11] = {
            ["id"] = 2764,
            ["name"] = "Throw",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/ability_throw",
        },
        [12] = {
            ["id"] = 3018,
            ["name"] = "Shoot",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/ability_marksmanship",
        },
    },
    ["shaman"] = {
        [1] = {
            ["id"] = 674,
            ["name"] = "Dual Wield",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/ability_dualwield",
        },
        [2] = {
            ["id"] = 199,
            ["name"] = "Two-Handed Maces",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/inv_mace_04",
        },
        [3] = {
            ["id"] = 197,
            ["name"] = "Two-Handed Axes",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/inv_axe_04",
        },
        [4] = {
            ["id"] = 198,
            ["name"] = "One-Handed Maces",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/inv_mace_01",
        },
        [5] = {
            ["id"] = 15590,
            ["name"] = "Fist Weapons",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/inv_gauntlets_04",
        },
        [6] = {
            ["id"] = 196,
            ["name"] = "One-Handed Axes",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/inv_axe_01",
        },
        [7] = {
            ["id"] = 227,
            ["name"] = "Staves",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/inv_staff_08",
        },
        [8] = {
            ["id"] = 107,
            ["name"] = "Block",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/ability_defend",
        },
        [9] = {
            ["id"] = 1180,
            ["name"] = "Daggers",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/ability_steelmelee",
        },
    },
    ["warlock"] = {
        [1] = {
            ["id"] = 227,
            ["name"] = "Staves",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/inv_staff_08",
        },
        [2] = {
            ["id"] = 201,
            ["name"] = "One-Handed Swords",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/ability_meleedamage",
        },
        [3] = {
            ["id"] = 1180,
            ["name"] = "Daggers",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/ability_steelmelee",
        },
        [4] = {
            ["id"] = 5019,
            ["name"] = "Shoot",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/ability_shootwand",
        },
        [5] = {
            ["id"] = 5009,
            ["name"] = "Wands",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/ability_shootwand",
        },
    },
    ["warrior"] = {
        [1] = {
            ["id"] = 674,
            ["name"] = "Dual Wield",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/ability_dualwield",
        },
        [2] = {
            ["id"] = 200,
            ["name"] = "Polearms",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/inv_spear_06",
        },
        [3] = {
            ["id"] = 199,
            ["name"] = "Two-Handed Maces",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/inv_mace_04",
        },
        [4] = {
            ["id"] = 197,
            ["name"] = "Two-Handed Axes",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/inv_axe_04",
        },
        [5] = {
            ["id"] = 198,
            ["name"] = "One-Handed Maces",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/inv_mace_01",
        },
        [6] = {
            ["id"] = 15590,
            ["name"] = "Fist Weapons",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/inv_gauntlets_04",
        },
        [7] = {
            ["id"] = 202,
            ["name"] = "Two-Handed Swords",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/ability_meleedamage",
        },
        [8] = {
            ["id"] = 196,
            ["name"] = "One-Handed Axes",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/inv_axe_01",
        },
        [9] = {
            ["id"] = 264,
            ["name"] = "Bows",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/inv_weapon_bow_05",
        },
        [10] = {
            ["id"] = 2567,
            ["name"] = "Thrown",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/inv_throwingknife_02",
        },
        [11] = {
            ["id"] = 227,
            ["name"] = "Staves",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/inv_staff_08",
        },
        [12] = {
            ["id"] = 201,
            ["name"] = "One-Handed Swords",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/ability_meleedamage",
        },
        [13] = {
            ["id"] = 107,
            ["name"] = "Block",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/ability_defend",
        },
        [14] = {
            ["id"] = 266,
            ["name"] = "Guns",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/inv_weapon_rifle_01",
        },
        [15] = {
            ["id"] = 5011,
            ["name"] = "Crossbows",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/inv_weapon_crossbow_01",
        },
        [16] = {
            ["id"] = 3127,
            ["name"] = "Parry",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/ability_parry",
        },
        [17] = {
            ["id"] = 1180,
            ["name"] = "Daggers",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/ability_steelmelee",
        },
        [18] = {
            ["id"] = 2764,
            ["name"] = "Throw",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/ability_throw",
        },
        [19] = {
            ["id"] = 3018,
            ["name"] = "Shoot",
            ["rank"] = 0,
            ["cost"] = 1000,
            ["texture"] = "Interface/ICONS/ability_marksmanship",
        }
    }    
}
